### ISSUE TITLE
z490 with i11900K

### ISSUE THREAD

**Issue by Nishant-Kathil** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#153] opened 2021-04-07 01:53 UTC
Hi @SchmockLord ,

I was running in overclocking mode for almost a year and now my desktop freezes randomly. May be something wrong with either CPU or motherboard.

I just wanted to check if either one of these parts get replaced, can this work with existing EFI?

like 

z490 + i11900K or
z590 + i10900K

**Comment by MiddlemanTM** [comment] 2021-04-07 05:13
If your board is freezing, the most likely issue is probably bad RAM. You can try testing your system using Memtest boot from a USB stick and see if any errors appear. If they do then the RAM should be replaced. Other issues could also be your CPU getting overheated by dried thermal paste not dissipating heat from the overclocking, in which case a thermal paste replacement is in order for both your CPU AND DGPU if you have one.

As for replacing the chips and or motherboard and getting it to work with the EFI, they shouldn't be a problem so long as they are marked as compatible with 10th and/or 11th gen. I have just upgraded my Z490 Aorus Xtreme from 10th gen i5 to i9-11900K and the EFI works just fine.

**Comment by gtrooper** [comment] 2021-04-07 07:38
You mean that you just updated the processor and it just booted without even spoofing the CPU-ID ?

**Comment by MiddlemanTM** [comment] 2021-04-08 07:33
Yes, although my EFI was already set for Coffee Lake (as I was running High Sierra on the i5). Only major change needed apart from dropping in the chip was the BIOS firmware to F20d.

**Comment by gtrooper** [comment] 2021-04-08 09:02
oh, thanks for confirming that. I thought that you should have at least try to fake the CPU-ID as SchmockLord did in his new Z590 i Vision D Build using the 11900k. I find it weird that it boots without this change though. Maybe something to do with Z490 Vs Z590 config.plist ? Anyway... its good to know that you cant at least update to 11900k using Z490. Do you use a PCIe 4.0 NVME SSD or a 3.0 one ?

**Comment by SchmockLord** [comment] 2021-04-08 09:40
@gtrooper Have you reset your NVRAM yet? If not, that might be a reason you are still able to boot the 11900k without a FakeCPU-ID.

**Comment by gtrooper** [comment] 2021-04-08 10:04
> @gtrooper Have you reset your NVRAM yet? If not, that might be a reason you are still able to boot the 11900k without a FakeCPU-ID.

I did not have the chance to try it yet @SchmockLord because i9 11900k has not arrived yet. I will update when it does. Thanks for your comment.

**Comment by Nishant-Kathil** [comment] 2021-04-08 16:18
Alright, so at-least a FakeCPU-ID is needed once we reset the NVRAM and use the existing EFI folders as is

**Comment by MiddlemanTM** [comment] 2021-04-08 23:20
> oh, thanks for confirming that. I thought that you should have at least try to fake the CPU-ID as SchmockLord did in his new Z590 i Vision D Build using the 11900k. I find it weird that it boots without this change though. Maybe something to do with Z490 Vs Z590 config.plist ? Anyway... its good to know that you can at least update to 11900k using Z490 with minimal to no changes at all. Do you use a PCIe 4.0 NVME SSD or a 3.0 one ?

What do you mean it doesn't need the change? Of course it did. I used a Coffee Lake CPUID for what was a Comet Lake CPU (i5 10500) in my settings in order to run High Sierra with Opencore - otherwise booting was impossible. But swapping the CPU out to 11th gen luckily didn't show much of a difference and still worked. The only issue I did find was with my Clover build of Catalina (than ran on the i5) that didn't work after the swap-out. So I had to change the EFI version to my OC version from High Sierra build instead. I have since updated the EFI to Comet Lake CPUID for both OSes and for Big Sur.

**Comment by MiddlemanTM** [comment] 2021-04-09 06:55
And to answer your other question I use both PCIe 3.0 & 4.0 SSDs on my setup and yes they work fine.

**Comment by gtrooper** [comment] 2021-04-09 07:57
> > oh, thanks for confirming that. I thought that you should have at least try to fake the CPU-ID as SchmockLord did in his new Z590 i Vision D Build using the 11900k. I find it weird that it boots without this change though. Maybe something to do with Z490 Vs Z590 config.plist ? Anyway... its good to know that you can at least update to 11900k using Z490 with minimal to no changes at all. Do you use a PCIe 4.0 NVME SSD or a 3.0 one ?
> 
> What do you mean it doesn't need the change? Of course it did. I used a Coffee Lake CPUID for what was a Comet Lake CPU (i5 10500) in my settings in order to run High Sierra with Opencore - otherwise booting was impossible. But swapping the CPU out to 11th gen luckily didn't show much of a difference and still worked. The only issue I did find was with my Clover build of Catalina (than ran on the i5) that didn't work after the swap-out. So I had to change the EFI version to my OC version from High Sierra build instead. I have since updated the EFI to Comet Lake CPUID for both OSes and for Big Sur.

I missed the "although my EFI was already set for Coffee Lake" thats why my answer. So... if you need to use a Coffee Lake CPUID to run High Sierra, how it is possible to still be able to boot High Sierra AFTER you change CPU-ID to Comet Lake in order to boot Catalina & Big Sur on 11900k ? I mean is there any way you define a different cpu-id for each OS you wanna boot somewhere in the config.plist ? I never tried multiple macos booting. Only windows and Linux along with macos. So I never had to fake the CPU-ID and I am still learning ! Thanks !

**Comment by MiddlemanTM** [comment] 2021-04-09 10:10
I change the CPUID because...it needs changing for the CPU used on the specific macOS being booted?

I think you are mistaking that I’m either a) booting all of the macOSes with a single EFI partition and/or b) having to use Comet Lake CPUID for High Sierra. No I’m not. The installations are all each on their own separate drives and the CPUID used for High Sierra is still Coffee Lake for the i9-11900K (except Mojave, Catalina & Big Sur). The reason for this is (and why it still works is) the i9 11th gen design still is based on the Skylake architecture (which is the basis of all macOS running Intel X86 code this past decade). It’s only some parts of it are backported from the Cypress Cove design, but otherwise it is Comet Lake parr’s as a base such as the PCI bridges. I confirmed this using Hackintool.

**Comment by gtrooper** [comment] 2021-04-09 10:48
Exactly, I thought that it was somehow possible to boot all these OS'es on the same SSD (That's why I asked HOW did you set up CPUID for each one.) Thanks for clarifying that to me. Choosing a different SSD is the easy route though. Something really nice and useful would be to be able to boot from Mac OS X Tiger TO macOS Big Sur on the same SSD. I know a lot of people who REALLY want to go to Big Sur BUT they are forced to RUN Ancient OS'es due to incompatible or abandoned apps. Although a really nice and simple way is to BUY External SATA or NVME SSD's and connect them via usb-A or C and use each SSD for a different OS. Anyway we are almost out of topic !  I want to ask you a question regarding your PCIe 4.0 SSD. Did you manage to get PCIe 4.0 SSD Speeds on a Z490 board ? SchmockLord said that although the Z490 boards are technically possible to run PCIe 4.0 on ONE of the THREE NVME SSD's, intel stated that in order to actually for this to work you need a Z590... Did you try to test the speed by using AJA System Lite or BlackMagic Disk ? Thank you for your contribution !

**Comment by MiddlemanTM** [comment] 2021-04-09 11:12
I see. Yeah well I guess now you know how it works!

As for the PCIe 4.0 drive, I haven't yet tested the speed on macOS on my drive (yet) because my drive is totally formatted running Windows at the moment. But I can say that I CAN see it on macOS Finder (NTFS partition), and in Windows AJA test my throughput has gone up by 2000MBps for the read alone to 4500MBps for the Gigabyte 1TB SSD installed (compared to PCIe 3, and it totally correlates with what PCIe 4.0 speeds (and the Gigabyte SSD spec) should be (which is 4500MBps).
FYI Gigabyte has just released a 7000MBps version of this SSD, so the speeds can go even higher.

Also I do know someone else by the name of Ori69 on the Tonymac forums had their PCIe 4.0 working in Big Sur on a Z590 board. Their read speeds went up to 6,000MBps on their 2TB SAMSUNG 980 PRO SSD!

**Comment by gtrooper** [comment] 2021-04-09 11:43
Yea, PCIe 4.0 Gen 1 Drives have maximum 5000MBPs and Gen 2 somewhere near 7000MBPs. I am aware about Samsung 980 Pro SSD Speeds but this drive is one of the worst regarding reliability and longevity because it uses TLC Caching... Even MLC is mediocre COMPARED to what SLC Caching offers to the table... look at the new ADATA drive I am attaching... Unbelievable performance, SLC Caching and 5 years warranty... It will probably be in stores the next 2 months. 

https://www.adata.com/us/xpg/830

Also, FYI, https://i.imgur.com/sPK213z.png

**Comment by g3d** [comment] 2021-04-12 05:59
@gtrooper let us know your observations. I'm also thinking about an upgrade to i11900K, but want to understand if I can get SSD boost or not without a new motherboard.

**Comment by SchmockLord** [comment] 2021-04-14 18:31
So with the Vision D and an 11th Gen CPU, you will get PCI4.0. But I think this is a Gigabyte Z490 only feature.

And to run an 11th Gen CPU on a Z490 on macOS, you need a FakeCPU-ID. And the iGPU doesn't work then.

**Comment by gtrooper** [comment] 2021-04-14 18:57
> So with the Vision D and an 11th Gen CPU, you will get PCI4.0. But I think this is a Gigabyte Z490 only feature.
> 
> And to run an 11th Gen CPU on a Z490 on macOS, you need a FakeCPU-ID. And the iGPU doesn't work then.

oh, this is not something I was expecting. It would be nice to use iGPU even for computing only... SchmockLord could you please tell us what CPU-ID we will need for the 11900K on Z490 ? Thanks !

**Comment by gtrooper** [comment] 2021-11-17 12:13
> So with the Vision D and an 11th Gen CPU, you will get PCI4.0. But I think this is a Gigabyte Z490 only feature.
> 
> And to run an 11th Gen CPU on a Z490 on macOS, you need a FakeCPU-ID. And the iGPU doesn't work then.

@SchmockLord Do you know if by using 11900K in this build Sidecar Works ? Is there any feature someone will lose if he updates to 11900K with Vision D Z490 ? Thanks !

**Comment by hoantv** [comment] 2022-10-12 17:31
> 
i am going to build a PC for hackintosh. I already have Z490 extreme. Do i need native mac wifi module and which is better 11900k or 10900k? thanks :)

**Comment by MiddlemanTM** [comment] 2022-10-13 06:41
@hoantv ,

Okay. Firstly the wifi and BT works as is using the OpenIntelWireless drivers from Github. But if you are using a native Mac wifi module it may help improve SideCar and/or Airdrop functionality (and you won't need extra drivers unlike Intel wifi/bt).

As for the CPU, personally I think the 10900K is a better chip overall for compatibility and speed. Whilst the speed increase is great on the 11900K for the PCIe 4.0 NVMe, the improvement is negligible because the TB4 chip takes a good 20% of the CPU overhead so you're left with a slower performing chip in general PLUS loss of use of the UHD 770 IGPU. With the 10900K you have all of that plus guaranteed macOS compatibility (including use of Sierra/High Sierra/Mojave using a Coffee Lake CPUID).

**Comment by hoantv** [comment] 2022-10-26 16:01
> @hoantv ,
> 
> Okay. Firstly the wifi and BT works as is using the OpenIntelWireless drivers from Github. But if you are using a native Mac wifi module it may help improve SideCar and/or Airdrop functionality (and you won't need extra drivers unlike Intel wifi/bt).
> 
> As for the CPU, personally I think the 10900K is a better chip overall for compatibility and speed. Whilst the speed increase is great on the 11900K for the PCIe 4.0 NVMe, the improvement is negligible because the TB4 chip takes a good 20% of the CPU overhead so you're left with a slower performing chip in general PLUS loss of use of the UHD 770 IGPU. With the 10900K you have all of that plus guaranteed macOS compatibility (including use of Sierra/High Sierra/Mojave using a Coffee Lake CPUID).

Thank you, i just got 10900KF :).

**Closed** 2024-12-20 18:54 UTC
